# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Solomon Messing
email: firstname.lastname@gmail.com
description: > # this means to ignore newlines until "url:"
  Research Scientist. Manager of data science for Social Science One at 
  Facebook, former (founding) Director at Pew Research Center’s Data Labs.

footer_text: # text at the bottom of the page
url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: SolomonMg # your GitHub user name
twitter_username: SolomonMg # your Twitter handle
linkedin_username: solomonmg # your LinkedIn user name
scholar_userid: to63kiAAAAAJ # your Google Scholar ID
orcid_id: # your ORCID ID
contact_note: >
  Email is the best way to reach me, but you'll have to prove you're human :)

google_analytics: UA-27273977-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: blog
blog_description: Thoughts on data visualization, analysis, & scientific research.

# Pagination
paginate: 10
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: solomonmessing # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]
exclude: [node_modules]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji
    - jekyll-twitter-plugin
    - jekyll-redirect-from


markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: r
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Jekyll-Scholar
scholar:

  last_name: Messing

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: cites.bib
  #bibliography_template: bib

  replace_strings: true
  #join_strings: true

  #details_dir: bibliography
  #details_layout: bibtex.html
  #details_link: Details

  #query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
